# Generated by Django 4.2.3 on 2023-07-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='tipos',
            new_name='tipo',
        ),
    ]
