# Generated by Django 4.2.3 on 2023-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_rename_tipos_conta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='essencial',
            field=models.BooleanField(default=True),
        ),
    ]
